name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != 'dhkatz/LethalAPI'
    steps:
      - uses: actions/checkout@v3
      - name: Download Lethal Company
        uses: dhkatz/steam-download@v1.1.0
        with:
          username: ${{ secrets.STEAM_USERNAME }}
          vdf: ${{ secrets.STEAM_VDF }}
          appid: 1966720
          path: ${{ github.workspace }}/LethalCompany
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Install dependencies
        run: dotnet restore
        env:
          LC_REFERENCES: "${{ github.workspace }}/LethalCompany/Lethal Company_Data/Managed"
      - name: Build
        run: dotnet build --configuration Release --no-restore
        env:
          LC_REFERENCES: "${{ github.workspace }}/LethalCompany/Lethal Company_Data/Managed"
      - uses: actions/upload-artifact@v3
        with:
          if-no-files-found: error
          path: "**/bin/**/LethalAPI.*.dll"
